# Generated by Django 2.2.6 on 2019-10-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0003_nsp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gorrayon',
            options={'verbose_name': 'Город и(или) Район', 'verbose_name_plural': 'Города и(или) Районы'},
        ),
        migrations.AlterModelOptions(
            name='nsp',
            options={'verbose_name': 'Населеный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterField(
            model_name='gorrayon',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='gorrayon',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Regions', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='nsp',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='nsp',
            name='rayon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.GorRayon', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='nsp',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Regions', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
