# Generated by Django 2.2.5 on 2019-10-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0005_auto_20191023_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsp',
            name='rayon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.GorRayon', verbose_name='Район'),
        ),
    ]
