# Generated by Django 2.2.5 on 2019-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0006_auto_20191023_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorrayon',
            name='region',
        ),
        migrations.AddField(
            model_name='gorrayon',
            name='region',
            field=models.ManyToManyField(null=True, to='rep_test_00.Regions', verbose_name='Регион'),
        ),
    ]
