# Generated by Django 2.2.5 on 2019-10-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0007_auto_20191023_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorrayon',
            name='region',
        ),
        migrations.AddField(
            model_name='gorrayon',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Regions', verbose_name='Регион'),
        ),
    ]
