# Generated by Django 2.2.5 on 2019-10-23 11:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0011_auto_20191023_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsp',
            old_name='region',
            new_name='region_n',
        ),
        migrations.AlterField(
            model_name='nsp',
            name='rayon',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region_n', chained_model_field='region_n', null=True, on_delete=django.db.models.deletion.CASCADE, to='rep_test_00.GorRayon'),
        ),
    ]
