# Generated by Django 2.2.5 on 2019-10-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0014_auto_20191029_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodOtrasl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('otrasl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Otrasl', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Подотрасль',
                'verbose_name_plural': 'Подотрасли',
            },
        ),
    ]
