# Generated by Django 2.2.5 on 2019-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0015_podotrasl'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsp',
            name='mo',
            field=models.BooleanField(null=True, verbose_name='Муниципальное образование'),
        ),
    ]
