# Generated by Django 2.2.5 on 2019-12-05 06:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0016_nsp_mo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('nsp', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='rayon', chained_model_field='rayon', null=True, on_delete=django.db.models.deletion.CASCADE, to='rep_test_00.Nsp', verbose_name='Населенный пункт')),
                ('rayon', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='rep_test_00.GorRayon', verbose_name='Район')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Regions', verbose_name='Регион')),
            ],
        ),
    ]
