# Generated by Django 2.2.5 on 2019-12-05 11:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0018_auto_20191205_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='otrasl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Otrasl', verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='org',
            name='pod_otrasl',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='otrasl', chained_model_field='otrasl', null=True, on_delete=django.db.models.deletion.CASCADE, to='rep_test_00.PodOtrasl', verbose_name='Подотрасль'),
        ),
    ]
