# Generated by Django 2.2.5 on 2020-01-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0022_auto_20191230_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('im', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('ot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('dolzhn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('inn_ruk', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН руководителя')),
                ('doc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Документ')),
                ('nom_doc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер документа')),
                ('dt_doc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата документа')),
                ('active', models.BooleanField(null=True, verbose_name='Действующий')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.Org', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
    ]
