# Generated by Django 2.2.6 on 2020-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0024_auto_20200214_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='uslugi',
            name='url_usl_on_site',
            field=models.URLField(null=True, verbose_name='Адрес на сайте'),
        ),
    ]
