# Generated by Django 2.2.6 on 2020-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0025_auto_20200216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='url_gosuslugi',
            field=models.URLField(null=True, verbose_name='Адрес госуслуги'),
        ),
    ]
