# Generated by Django 2.2.6 on 2020-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0026_auto_20200216_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Стоимость услуги'),
        ),
    ]
