# Generated by Django 2.2.5 on 2020-03-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0027_auto_20200216_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uslugi',
            old_name='cat_uslugi',
            new_name='cat_usl',
        ),
        migrations.AlterField(
            model_name='org',
            name='cat_uslugi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rep_test_00.CatUslugi', verbose_name='Категория услуги'),
        ),
    ]
