# Generated by Django 2.2.5 on 2020-03-18 11:11

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0028_auto_20200318_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='viduslugi',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='добавляем категории'),
        ),
        migrations.AlterField(
            model_name='org',
            name='vid_uslugi',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cat_uslugi', chained_model_field='cat_usl', null=True, on_delete=django.db.models.deletion.CASCADE, to='rep_test_00.VidUslugi', verbose_name='Вид услуги'),
        ),
        migrations.AlterField(
            model_name='uslugi',
            name='url_usl_on_site',
            field=models.URLField(null=True, verbose_name='Адрес на сайте региона'),
        ),
    ]
