# Generated by Django 2.2.5 on 2020-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0029_auto_20200318_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='cat_uslugi',
        ),
        migrations.RemoveField(
            model_name='org',
            name='vid_uslugi',
        ),
        migrations.RemoveField(
            model_name='viduslugi',
            name='test',
        ),
        migrations.AddField(
            model_name='viduslugi',
            name='pod_otr_txt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подотрасли (через запятую)'),
        ),
    ]
