# Generated by Django 2.2.6 on 2020-04-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_test_00', '0030_auto_20200318_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='org',
            name='okved',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='org',
            name='okved_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ОКВЭД наименование'),
        ),
    ]
